# Generated by Django 4.2.8 on 2023-12-21 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(help_text='Введите название факультета', max_length=50, verbose_name='Факультет')),
                ('description', models.CharField(help_text='Введите описание', max_length=200, verbose_name='Описание фаультета')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя группы', max_length=7, unique=True, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(help_text='Введите фамилию', max_length=40, verbose_name='Фамилия')),
                ('name', models.CharField(help_text='Введите имя', max_length=40, verbose_name='Имя')),
                ('thirdname', models.CharField(help_text='Введите отчество', max_length=40, verbose_name='Отчетство')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название предмета', max_length=30, verbose_name='Предмет')),
                ('description', models.CharField(help_text='Введите описание предмета', max_length=100, verbose_name='Описание предмета')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.faculty', verbose_name='Факультет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': ('Предмет',),
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(help_text='Введите фамилию', max_length=40, verbose_name='Фамилия')),
                ('name', models.CharField(help_text='Введите имя', max_length=40, verbose_name='Имя')),
                ('number_id', models.CharField(help_text='Введите поименный номер(пример: st00001)', max_length=7, unique=True)),
                ('telephone', models.CharField(help_text='Введите ваш номер телефона', max_length=12, unique=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g1', models.IntegerField()),
                ('g2', models.IntegerField()),
                ('g3', models.IntegerField()),
                ('g4', models.IntegerField()),
                ('g5', models.IntegerField()),
                ('g6', models.IntegerField()),
                ('g7', models.IntegerField()),
                ('g8', models.IntegerField()),
                ('g9', models.IntegerField()),
                ('g10', models.IntegerField()),
                ('num_of_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.student', verbose_name='Поименный номер')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Успеваемость',
                'verbose_name_plural': 'Успеваемости',
            },
        ),
    ]
