# Generated by Django 4.2.7 on 2023-12-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': ('Факультет',), 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterField(
            model_name='faculty',
            name='description',
            field=models.CharField(help_text='Введите описание', max_length=2000, verbose_name='Описание фаультета'),
        ),
    ]
